### PR TITLE
Added path exporting for other buildpacks

### PR DESCRIPTION
**Pull request by ruscoder**

### CODE REVIEW

**Comment by siboulet** [comment]
If I get this right you need to add the LD_LIBRARY_PATH and PATH exports to the build environment so that these variables are available to chained buildpacks?

What is LP_DIR for?

Why not simply source $PROFILE_PATH instead of duplicating exports?

**Comment by ruscoder** [comment]
@siboulet i am agree with you, i have copied from other buildpacks hastily for inner uses. I will rewrite this in near future and resend merge request

**Comment by siboulet** [comment]
@ruscoder but what do you need LP_DIR for?

**Comment by ruscoder** [comment]
@siboulet it is buildpack dir, and we are write to <buildpackdir>/export file our vars which are available for chained buildpacks. It is analogue with https://github.com/heroku/heroku-buildpack-nodejs/blob/bfb75db690c4c19f8a028f9edea6e01723dfd234/lib/environment.sh#L42 and https://github.com/heroku/heroku-buildpack-nodejs/blob/56860c2792d15fb1340faf792fe356e40bd8d8d0/bin/compile#L20

**Pull request closed without merging**
